import { z } from "zod";
import { readCardMemory } from "./cards";
const cardSchema=z.object({format:z.enum(["yaml","json"]),filename:z.string().max(180),source:z.string().max(60000)}).strict().superRefine((card,ctx)=>{try{readCardMemory(card)}catch(error){ctx.addIssue({code:"custom",message:(error as Error).message})}});
const short=z.string().trim().max(2000);
export const playerStateSchema=z.object({location:short,clothing:short,condition:short,inventory:short}).strict();
export const stateSchema=z.object({location:short,clothing:short,condition:short,emotion:short,thought:short,goal:short,relationship:short}).strict();
export const memorySchema=z.object({id:z.string(),turnId:z.string(),content:short,kind:z.enum(["observation","belief"]),importance:z.number().int().min(1).max(5),source:z.object({type:z.enum(["event","statement","inference"]),eventIndex:z.number().int().nonnegative().optional(),speaker:z.string().max(80).optional()}).strict().optional(),tags:z.array(z.string().max(80)).max(20).optional(),status:z.enum(["active","superseded","resolved"]).optional(),supersedes:z.array(z.string()).max(20).optional(),scope:z.enum(["durable","scene","transient"]).optional(),validFromTurnId:z.string().optional(),validUntilTurnId:z.string().optional()}).strict();
export const characterSchema=z.object({id:z.string().min(1).max(80),name:z.string().trim().min(1).max(40),role:short,persona:z.string().max(6000),secret:z.string().max(4000),color:z.enum(["amber","blue","gray"]),modelId:z.string().max(100),presetId:z.string().max(100).default("inherit"),card:cardSchema.optional(),state:stateSchema,memories:z.array(memorySchema).max(2000)}).strict();
const threadSchema=z.object({id:z.string(),description:z.string().max(1000),characterIds:z.array(z.string().max(80)).max(6),status:z.enum(["open","resolved"]),openedTurnId:z.string(),resolvedTurnId:z.string().optional(),sourceEventIndex:z.number().int().nonnegative().optional()}).strict();
const summarySchema=z.object({id:z.string(),content:z.string().max(6000),sourceTurnIds:z.array(z.string()).max(50),createdTurnId:z.string(),level:z.enum(["scene","chapter"])}).strict();
const contextSchema=z.object({threads:z.array(threadSchema).max(200),sceneSummaries:z.array(summarySchema).max(80),chapterSummaries:z.array(summarySchema).max(30)}).strict().default({threads:[],sceneSummaries:[],chapterSummaries:[]});
export const storySchema=z.object({title:z.string().trim().min(1).max(80),world:z.string().max(12000),opening:z.string().max(12000),player:z.string().trim().min(1).max(40),playerPersona:z.string().max(6000),playerState:playerStateSchema.default({location:"当前场景",clothing:"日常服饰",condition:"健康",inventory:""}),style:z.string().max(4000),presetSelection:z.object({director:z.string().max(100).default(""),actor:z.string().max(100).default(""),settlement:z.string().max(100).default(""),narrator:z.string().max(100).default(""),memory:z.string().max(100).default("")}).strict().default({director:"",actor:"",settlement:"",narrator:"",memory:""}),stageModels:z.object({settlement:z.string().max(100).default(""),narrator:z.string().max(100).default(""),memory:z.string().max(100).default("")}).strict().default({settlement:"",narrator:"",memory:""}),collaborationMode:z.enum(["economy","balanced","precise"]).default("balanced"),retrieval:z.object({mode:z.enum(["lexical","hybrid"]),embeddingProfileId:z.string().max(100),embeddingModel:z.string().trim().max(150)}).strict().default({mode:"lexical",embeddingProfileId:"",embeddingModel:""}),context:contextSchema,characters:z.array(characterSchema).max(6)}).strict().refine(s=>new Set(s.characters.map(c=>c.id)).size===s.characters.length,"角色 ID 不可重复");
export const profileSchema=z.object({id:z.string().max(100),name:z.string().trim().min(1).max(80),provider:z.enum(["openai","compatible","anthropic","gemini"]),baseUrl:z.string().url().max(500),model:z.string().trim().min(1).max(150),contextWindow:z.number().int().min(1024).max(2000000).optional(),structuredOutput:z.boolean().optional(),apiKey:z.string().trim().max(4000).optional(),clearKey:z.boolean().optional()}).strict();
export const turnSchema=z.object({storyId:z.string(),revision:z.number().int().nonnegative(),input:z.string().trim().min(1).max(8000),mode:z.enum(["roleplay","director"]),regenerate:z.boolean().optional(),requestId:z.string().uuid()}).strict();
export class AppError extends Error { constructor(message:string,public status=400){super(message)} }
export function ancestry<T extends {id:string;parentId:string|null}>(all:T[],head:string|null):T[]{const map=new Map(all.map(t=>[t.id,t]));const path:T[]=[];const seen=new Set<string>();while(head){if(seen.has(head))throw new AppError("剧情分支存在循环",500);seen.add(head);const t=map.get(head);if(!t)throw new AppError("剧情分支缺少回合",500);path.unshift(t);head=t.parentId;}return path;}


