"use client";
import { useState } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { importPreset, exportPreset, orderGroups, presetSchema, presetWarnings, type Preset, type PresetEntry } from "@/lib/tavern/presets";
import type { Workspace } from "@/lib/tavern/types";
import { EditorSelect, downloadText } from "./editor-controls";

const entry=():PresetEntry=>({identifier:crypto.randomUUID(),name:"新提示词",role:"system",content:"",enabled:true,marker:false,position:0,depth:4,order:100,triggers:[]});
const blank=():Preset=>({id:"",revision:0,name:"新预设",source:"MyTavern",entries:[entry()],sampling:{},sourceWarnings:[]});
async function request<T>(method:string,body?:unknown,id?:string):Promise<T>{const r=await fetch("/api/presets"+(id?"?id="+encodeURIComponent(id):""),{method,headers:{"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||"预设操作失败。");return data;}
export function PresetManager({workspace,onClose,onRefresh,onAssign}:{workspace:Workspace;onClose:()=>void;onRefresh:()=>Promise<void>;onAssign:(stage:"director"|"actor"|"narrator",id:string)=>Promise<void>}) {
 const [draft,setDraft]=useState<Preset>(blank);const [baseline,setBaseline]=useState(()=>JSON.stringify(draft));const [selected,setSelected]=useState(0);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [pending,setPending]=useState<{title:string;description:string;run:()=>void}|null>(null);
 const [importFile,setImportFile]=useState<{text:string;name:string;groups:ReturnType<typeof orderGroups>}|null>(null);const [group,setGroup]=useState("0");
 const dirty=JSON.stringify(draft)!==baseline;const current=draft.entries[selected];const warnings=presetWarnings(draft);
 const adopt=(p:Preset)=>{setDraft(p);setBaseline(JSON.stringify(p));setSelected(0);setError("")};
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError("");try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 const guard=(run:()=>void)=>{if(dirty)setPending({title:"放弃未保存的预设修改？",description:"当前草稿尚未保存，继续会放弃这些修改。",run});else run()};
 function patch(value:Partial<PresetEntry>){setDraft(p=>({...p,entries:p.entries.map((e,i)=>i===selected?{...e,...value}:e)}))}
 function move(offset:number){const to=selected+offset;if(to<0||to>=draft.entries.length)return;const entries=[...draft.entries];[entries[selected],entries[to]]=[entries[to],entries[selected]];setDraft({...draft,entries});setSelected(to)}
 return <><Dialog open onOpenChange={open=>{if(!open&&!busy)guard(onClose)}}><DialogContent className="editor-dialog preset-dialog"><DialogHeader><DialogTitle>预设管理</DialogTitle><DialogDescription>管理提示词、排列顺序和生成参数。保存后，所有引用此预设的角色与阶段在下一回合使用新版本。</DialogDescription></DialogHeader>
 {error&&<p className="error-banner" role="alert">{error}</p>}
 <fieldset disabled={busy} className="preset-fieldset"><div className="preset-assignments">{(["director","actor","narrator"] as const).map((stage,i)=><EditorSelect key={stage} disabled={busy} label={["导演预设","角色默认预设","旁白预设"][i]} value={workspace.story.presetSelection?.[stage]||""} onChange={id=>void act(()=>onAssign(stage,id))} options={[{value:"",label:"不使用预设"},...workspace.presets.map(p=>({value:p.id,label:p.name}))]}/>)}</div>
 <div className="preset-toolbar"><EditorSelect disabled={busy} label="已保存的预设" value={draft.id} onChange={id=>guard(()=>{if(id)void act(async()=>adopt(await request<Preset>("GET",undefined,id)));else adopt(blank())})} options={[{value:"",label:"新建 / 导入草稿"},...workspace.presets.map(p=>({value:p.id,label:p.name+` · v${p.revision}`}))]}/><Button type="button" variant="outline" onClick={()=>guard(()=>adopt(blank()))}>新建预设</Button><Button type="button" variant="outline" onClick={()=>{setDraft({...draft,id:"",revision:0,name:(draft.name+" 副本").slice(0,120)});setBaseline("")}}>复制</Button></div>
 <label className="field"><span>导入 SillyTavern Chat Completion 预设（JSON）</span><input type="file" accept=".json" onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(!file)return;guard(()=>void act(async()=>{if(file.size>2*1024*1024)throw new Error("文件超过 2 MB。");const text=await file.text();const groups=orderGroups(text);if(groups.length>1){setImportFile({text,name:file.name,groups});setGroup("0")}else{adopt(importPreset(text,file.name));setBaseline("")}}))}}/></label>
 {importFile&&<div className="model-control"><EditorSelect label="导入顺序组" value={group} onChange={setGroup} options={importFile.groups.map(g=>({value:String(g.index),label:g.label}))}/><Button type="button" onClick={()=>void act(async()=>{adopt(importPreset(importFile.text,importFile.name,Number(group)));setBaseline("");setImportFile(null)})}>导入所选顺序组</Button><Button variant="ghost" type="button" onClick={()=>setImportFile(null)}>取消导入</Button></div>}
 <label className="field"><span>预设名称{dirty?" · 未保存":""}</span><input maxLength={120} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
 <Tabs defaultValue="prompts"><TabsList><TabsTrigger value="prompts">提示词条目 · {draft.entries.length}</TabsTrigger><TabsTrigger value="sampling">生成参数</TabsTrigger><TabsTrigger value="warnings">兼容提示 · {warnings.length}</TabsTrigger></TabsList>
 <TabsContent value="prompts"><div className="prompt-layout"><div className="prompt-list" aria-label="提示词列表">{draft.entries.map((item,i)=><button type="button" key={i} className={i===selected?"active":""} onClick={()=>setSelected(i)}><span>{i+1}. {item.name||item.identifier}</span><small>{item.enabled?"启用":"关闭"} · {item.marker?"动态标记":item.role}</small></button>)}<Button type="button" variant="outline" disabled={draft.entries.length>=300} onClick={()=>{setSelected(draft.entries.length);setDraft({...draft,entries:[...draft.entries,entry()]})}}>添加提示词</Button></div>
 {current&&<div className="prompt-editor"><div className="form-buttons"><Button type="button" variant="outline" disabled={!selected} onClick={()=>move(-1)}>上移</Button><Button type="button" variant="outline" disabled={selected===draft.entries.length-1} onClick={()=>move(1)}>下移</Button><Button type="button" variant="ghost" disabled={draft.entries.length===1} onClick={()=>{setDraft({...draft,entries:draft.entries.filter((_,i)=>i!==selected)});setSelected(Math.max(0,selected-1))}}>移除条目</Button></div>
 <label className="switch-label">启用此条目<Switch disabled={busy} aria-label="启用此条目" checked={current.enabled} onCheckedChange={enabled=>patch({enabled})}/></label><label className="field"><span>条目名称</span><input value={current.name} maxLength={160} onChange={e=>patch({name:e.target.value})}/></label><label className="field"><span>标识符（identifier）</span><input value={current.identifier} maxLength={150} onChange={e=>patch({identifier:e.target.value})}/></label>
 <EditorSelect disabled={busy} label="消息角色" value={current.role} onChange={role=>patch({role:role as PresetEntry["role"]})} options={[{value:"system",label:"System · 系统"},{value:"user",label:"User · 用户"},{value:"assistant",label:"Assistant · 助手"}]}/>
 <label className="switch-label">动态标记<Switch disabled={busy} aria-label="动态标记" checked={current.marker} onCheckedChange={marker=>patch({marker})}/></label>
 {current.marker?<p className="form-help">使用标识符填入动态内容：chatHistory、charDescription、charPersonality、personaDescription、scenario、worldInfoBefore、worldInfoAfter、dialogueExamples。</p>:<label className="field"><span>提示词内容</span><textarea className="source-editor" rows={10} maxLength={32000} value={current.content} onChange={e=>patch({content:e.target.value})}/></label>}
 <EditorSelect disabled={busy||current.marker} label="注入位置" value={String(current.position)} onChange={v=>patch({position:Number(v) as 0|1})} options={[{value:"0",label:"按列表顺序"},{value:"1",label:"插入可见历史"}]}/>
 {current.position===1&&!current.marker&&<div className="form-grid"><label className="field"><span>历史深度（0 为末尾）</span><input type="number" min={0} max={100} value={current.depth} onChange={e=>patch({depth:Number(e.target.value)})}/></label><label className="field"><span>同深度排序值</span><input type="number" min={0} max={10000} value={current.order} onChange={e=>patch({order:Number(e.target.value)})}/></label></div>}
 <label className="field"><span>触发类型（逗号分隔；留空为全部）</span><input placeholder="normal, regenerate" value={current.triggers.join(",")} onChange={e=>patch({triggers:e.target.value?e.target.value.split(","):[]})}/></label></div>}</div></TabsContent>
 <TabsContent value="sampling"><p className="form-help">留空使用服务商默认值。输出上限留空使用平台默认值，实际参数支持以服务商为准。</p><div className="form-grid">{([{key:"temperature",label:"Temperature · 温度",min:0,max:2,step:0.05},{key:"topP",label:"Top P",min:0,max:1,step:0.05},{key:"maxTokens",label:"最大输出 Token",min:1,max:32000,step:1},{key:"frequencyPenalty",label:"频率惩罚",min:-2,max:2,step:0.1},{key:"presencePenalty",label:"存在惩罚",min:-2,max:2,step:0.1}] as const).map(p=><label className="field" key={p.key}><span>{p.label}</span><input type="number" min={p.min} max={p.max} step={p.step} value={draft.sampling[p.key]??""} onChange={e=>setDraft({...draft,sampling:{...draft.sampling,[p.key]:e.target.value===""?undefined:Number(e.target.value)}})}/></label>)}</div></TabsContent>
 <TabsContent value="warnings"><p className="form-help">支持 Chat Completion 提示词与常用宏。正则、脚本及酒馆助手扩展不执行。角色可见历史受信息分发限制。</p>{warnings.length?warnings.map((w,i)=><p className="preset-warning" key={i}>{w}</p>):<p className="success-message">当前没有兼容提示。</p>}</TabsContent></Tabs>
 <div className="form-buttons preset-save"><Button disabled={busy} type="button" onClick={()=>void act(async()=>{const validated=presetSchema.safeParse(draft);if(!validated.success)throw new Error(validated.error.issues.map(i=>i.path.join(".")+"："+i.message).slice(0,3).join("；"));const saved=await request<Preset>("POST",validated.data);adopt(saved);await onRefresh();toast.success("预设已保存，下次生成生效。")})}>{busy?"处理中…":"保存预设"}</Button><Button type="button" variant="outline" onClick={()=>void act(async()=>{const p=presetSchema.parse(draft);downloadText(p.name+".json",JSON.stringify(exportPreset(p),null,2))})}>导出 JSON</Button>{draft.id&&<Button type="button" variant="ghost" onClick={()=>setPending({title:"删除这份预设？",description:"删除后无法恢复。仍被故事或历史版本引用的预设会保留。",run:()=>void act(async()=>{await request("DELETE",{id:draft.id,revision:draft.revision});adopt(blank());await onRefresh();toast.success("预设已删除。")})})}>删除预设</Button>}</div></fieldset>
 </DialogContent></Dialog><AlertDialog open={!!pending} onOpenChange={open=>{if(!open)setPending(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending?.title}</AlertDialogTitle><AlertDialogDescription>{pending?.description}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>取消</AlertDialogCancel><AlertDialogAction onClick={()=>{const run=pending?.run;setPending(null);run?.()}}>继续</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
